### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by lbluque** [MJCliffe/PASCal#15]
Hi @ml-evs  and @MJCliffe 

I'm adding my review comments for openjournals/joss-reviews#5556 here.

Overall, the latest updates to the source code and documentation look great. I found it very straightforward to use the web tool and the API directly.

Specific comments:

### General

- Can you clarify the contributions of the first author M.L.? I notice they do not show up in the commit history.

### Functionality

- I had no problem running the app locally or accessing it on https://www.pascalapp.co.uk; however, the link in the README https://pascalapp.co.uk is not working for me. 

### Documentation

- The web tool link in the documentation is somewhat hard to make out. It might be helpful to have a link to the web app more prominently located.
- I noticed the CI tests use Python 3.9, does the software run in newer versions? I think you should mention supported Python versions; additionally, since your unit tests run quite quickly you can run tests using all supported Python versions.
- I suggest adding a search bar to the documentation. I personally find it extremely helpful to be able to quickly reference API.
- The contributing page is very informative, though I would add the following details for developers: how to install with additional testing requirements and the recommended way to run tests. Personally, I have never used poetry, so this would be helpful to have mentioned upfront.

### Paper

- I noticed you have a list of other useful software in the documentation. It would be useful to have these and any other related software included in the paper, along with a brief discussion of how PASCal compares.

**Comment by MJCliffe** [comment]
Thanks! We'll get workin on the issues, which seem sensible and manageable.

Regarding the contribution of Monthakan (ML), she wrote the initial version offline as a summer project, which formed the basis of the first functional version uploaded to github. Her summer project has finished so she is no longer an active contributor.

**Comment by ml-evs** [comment]
Thanks @lbluque, all good suggestions. #16 should address the suggestions on the docs/testing front.

**Comment by MJCliffe** [comment]
Final small changes made Paper updated and link to https://pascalapp.co.uk replaced by https://www.pascalapp.co.uk in the docs.

**Comment by lbluque** [comment]
> Thanks! We'll get workin on the issues, which seem sensible and manageable.
> 
> Regarding the contribution of Monthakan (ML), she wrote the initial version offline as a summer project, which formed the basis of the first functional version uploaded to github. Her summer project has finished so she is no longer an active contributor.

Ok, that makes sense. Thanks for clarifying!

**Comment by lbluque** [comment]
Just went over the edits. Everything looks great. I really like the look of the documentation!

**Comment by ml-evs** [comment]
Thanks, closing this now then!
