### ISSUE TITLE
Logo writing hard to see for GitHub "darnk mode" users

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [MJCliffe/PASCal#25]
When GitHub is used in "dark mode", as many developers do, your logo is hard to make out and appears like this: 

![Screenshot from 2023-10-23 11-39-38](https://github.com/MJCliffe/PASCal/assets/8392709/0816fdcf-4344-4301-b918-cd62d61a8370)

A sticker-like version would help it stand out more so it would look like: 
![Screenshot from 2023-10-23 11-52-38](https://github.com/MJCliffe/PASCal/assets/8392709/43475a80-1241-472f-ad0e-78868accfd77)

Source of "sticker like" design (I used GIMP to select-grow-fill the white region): 

![PASCaL_01](https://github.com/MJCliffe/PASCal/assets/8392709/79767e1a-a82d-4f75-ab7a-9c974863dbb9)

**Comment by Kevin-Mattheus-Moerman** [comment]
Note I am a JOSS editor, but the above is absolutely not required for the JOSS publication you are pursuing. Just a small recommendation from me personally when I noticed the text in the logo was difficult to read.

**Comment by MJCliffe** [comment]
Hi @Kevin-Mattheus-Moerman  - thanks for the suggestion. I've now uploaded a new 'sticker' type logo, which is much more readable in dark mode and looks quite nifty too!
